[config]
schemaVersion = "0.0.1"

[package]
namespace = "innominata"
name = "StarsandBehemoth"
versionNumber = "1.0.0"
description = "Adds a Behemoth Scolomorph as a random spawn"
websiteUrl = "https://github.com/innominata/StarsandBehemoth"
containsNsfwContent = false

[package.dependencies]
"BepInEx-BepInExPack_Starsand"= "5.4.16"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./"

[[build.copy]]
source = "./obj/Debug/net472/StarsandBehemoth.dll"
target = "./StarsandBehemoth.dll"
[publish]
repository = "https://starsand.thunderstore.io"
communities = ["starsand"]
categories = []